### ISSUE TITLE
Go Error : Even thought I have go installed

### ISSUE THREAD

**Issue by Xload12** [micha3lb3n/SSRFire#1]
Hi, 

Though I have Go and python 3.7 installed, I'm getting this error during ./setup.sh

![3k](https://user-images.githubusercontent.com/65593383/82303277-5bc76000-99d8-11ea-88a6-8f9e0235b264.png)
![2k](https://user-images.githubusercontent.com/65593383/82303288-608c1400-99d8-11ea-9063-2e1de67431e1.png)
![1k](https://user-images.githubusercontent.com/65593383/82303300-62ee6e00-99d8-11ea-8995-c257be0786b0.png)

Kindly provide the workaround for this.

Thanks,

**Comment by micha3lb3n** [comment]
Hi @Xload12 ,

Those are not error messages, but they are precautionary warnings. Everything works fine for you. You are good to run ssrfire.sh now !

Regards
Micha3lb3n
