### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by qodirovhamidjon** [micha3lb3n/SSRFire#2]
`The final URL list is at output/seclub.org/final_urls.txt

Total URLs fetched with parameters: 7668
Do you want to check for SSRF: [y/n] y

Firing requests, check your server for any traffic!
Encountered error(s): 2 errors occured.
        * -u flag or -request flag is required
        * Either -w or --input-cmd flag is required

Done!

WARNING: Testing for XSS generates a lot of noise. You must test only those sites on which you are authorised to.
Do you want to check for XSS: [y/n]
`

**Comment by micha3lb3n** [comment]
Hi @qodirovhamidjon , 

It seems there's a problem with your path configuration for ffuf.

Do the following:
1. Check whether a .profile has been created in the SSRFire directory. It is a hidden file, you can make it visible using ctrl + H in the files or using ls -all in the terminal. If there is no .profile, you haven't run setup.sh

2. If yes, ensure that your .profile looks like this.
![Screenshot (10)](https://user-images.githubusercontent.com/62587318/82575443-19ec1480-9ba6-11ea-8cb9-c84ae63c16eb.png)
If no, remove the tools directory using rm -rf tools, and run setup.sh again.

3. If both the above steps don't solve your problem, there's some problem while running setup.sh. I can comment more only if I have screenshots of the output of setup.sh

I am currently closing the issue. If you still facing any problems, comment below with more information, and I'll reopen the issue.

Regards
Micha3lb3n
