### ISSUE TITLE
not found during ./ssrfire.sh

### ISSUE THREAD

**Issue by shripad5258** [micha3lb3n/SSRFire#9]
![image](https://user-images.githubusercontent.com/65358061/103226362-eea68080-4951-11eb-80d0-ce0c7fd652e5.png)
command like -./ssrfire.sh -d domain.com -s myserver.com

**Comment by micha3lb3n** [comment]
Can you mention your OS and linux distribution and what command caused this error?

**Comment by shripad5258** [comment]
yes 
kali linux debian
thanks

**Comment by micha3lb3n** [comment]
It runs fine on my debian distribution and it is supposed to do the same for you as well.

From the screenshot, it is seen that your terminal is not recognizing basic bash commands. So, are you running bash?

If not running bash, this works only on bash

If running bash, refer [https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found](https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found)

**Comment by shripad5258** [comment]
Thanks brother
im using zsh so doesnt work in zsh shell but when i tried in bash yehh its works 
finally problem solved thnks

**Comment by micha3lb3n** [comment]
😀

**Comment by alegra8611** [comment]
If your are using zsh, you need to append .profile to .zshrc in the ssrfire script
